// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaYjMVMZldkkcUf0_weK4qXM1t1N1OjME',
    appId: '1:978336912790:web:c1ab94cc3670bf6a93f9b7',
    messagingSenderId: '978336912790',
    projectId: 'first-application-d66ec',
    authDomain: 'first-application-d66ec.firebaseapp.com',
    storageBucket: 'first-application-d66ec.firebasestorage.app',
    measurementId: 'G-1SQR9F4CJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRnl6vUJ5QcIA166cwYx1CiVXUt5BW6Hg',
    appId: '1:978336912790:android:8da86e124b92708a93f9b7',
    messagingSenderId: '978336912790',
    projectId: 'first-application-d66ec',
    storageBucket: 'first-application-d66ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HMMOXgOnrDKIIh8_YEPY7SXAA4WDb6o',
    appId: '1:978336912790:ios:617acd58c7055cb593f9b7',
    messagingSenderId: '978336912790',
    projectId: 'first-application-d66ec',
    storageBucket: 'first-application-d66ec.firebasestorage.app',
    iosBundleId: 'com.example.firstApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HMMOXgOnrDKIIh8_YEPY7SXAA4WDb6o',
    appId: '1:978336912790:ios:617acd58c7055cb593f9b7',
    messagingSenderId: '978336912790',
    projectId: 'first-application-d66ec',
    storageBucket: 'first-application-d66ec.firebasestorage.app',
    iosBundleId: 'com.example.firstApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaYjMVMZldkkcUf0_weK4qXM1t1N1OjME',
    appId: '1:978336912790:web:3a0b79113b2ea49593f9b7',
    messagingSenderId: '978336912790',
    projectId: 'first-application-d66ec',
    authDomain: 'first-application-d66ec.firebaseapp.com',
    storageBucket: 'first-application-d66ec.firebasestorage.app',
    measurementId: 'G-QB4BLC66PC',
  );
}
